### ISSUE TITLE
How many GPU resources does this task require in total?

### ISSUE THREAD

**Issue by Yufccode** [haomo-ai/Cam4DOcc#6]
Hi! I noticed that your script uses 8 GPUs for training and testing simultaneously. How many GPU resources are needed to reproduce the results of this task, training and testing, in totally?  Thanks for noticing this issue！

**Comment by BIT-MJY** [comment]
hi @Yufccode Thanks for your interest in our code. Large GPU memory (e.g., 80G) is necessary for possibly using our model while the number of GPU mainly affects the training and test efficiency.

**Comment by Yufccode** [comment]
thank you for your answer 🌹@BIT-MJY
