### ISSUE TITLE
Wrap feature possible issue

### ISSUE THREAD

**Issue by synsin0** [haomo-ai/Cam4DOcc#9]
In line 293 of ocfnet.py， I think the transformed_grid.shape[1]=4, which may indicate you only wrap 4 voxel grid feature to the wraped_x from x. I don't know if I understand right, I think the for loop should be the number of voxels. May you check again this part?

**Comment by BIT-MJY** [comment]
@synsin0 thanks for your reminder! we fixed it in the latest version.
